name: Build Docker image

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag'
        required: false
        default: 'master'
        type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          ref: master  # First checkout master to get DockerfileSlim

      - name: Save DockerfileSlim
        run: |
          mkdir -p /tmp/docker
          cp DockerfileSlim /tmp/docker/

      - name: Checkout target ref
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          clean: true

      - name: Restore DockerfileSlim
        run: cp /tmp/docker/DockerfileSlim ./

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: extract-image-version
        run: echo version=$(echo ${{ inputs.ref }} | sed 's/v//') >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/seleniumbase
          tags: type=raw,value=${{ steps.extract-image-version.outputs.version }}
      
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: DockerfileSlim
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}