name: Sync fork

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    outputs:
      refs: ${{ steps.extract-tags.outputs.refs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Configure repo
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git remote add upstream https://github.com/seleniumbase/SeleniumBase.git
      - name: Extract list of new tags
        id: extract-tags
        run: |
          git fetch upstream --tags
          echo "=== Upstream tags ==="
          # Get all upstream version tags and get the newest one
          UPSTREAM_TAGS=$(git ls-remote --tags upstream | grep 'refs/tags/v[0-9]' | sed 's/.*refs\/tags\///' | sort -V)
          NEWEST_TAG=$(echo "$UPSTREAM_TAGS" | tail -n1)
          echo "Upstream tags found:"
          echo "$UPSTREAM_TAGS"
          echo "Newest tag: $NEWEST_TAG"
          
          # Create JSON array with master and newest tag
          TAGS_JSON="[\"master\", \"$NEWEST_TAG\"]"
          echo "Final JSON array:"
          echo "$TAGS_JSON"
          echo "refs=$TAGS_JSON" >> "$GITHUB_OUTPUT"
      
      - name: Print refs to be processed
        run: |
          echo "Raw refs output:"
          echo ${{ steps.extract-tags.outputs.refs }}
      - name: Rebase
        run: |
          # Save current files to temp location
          mkdir -p /tmp/workflows
          cp .github/workflows/sync-fork.yml /tmp/workflows/
          cp .github/workflows/build-docker-image.yml /tmp/workflows/
          cp DockerfileSlim /tmp/workflows/
          
          # Sync with upstream
          git fetch upstream
          git fetch --tags upstream
          git reset --hard upstream/master
          
          # Restore our custom files
          mkdir -p .github/workflows
          cp /tmp/workflows/sync-fork.yml .github/workflows/
          cp /tmp/workflows/build-docker-image.yml .github/workflows/
          cp /tmp/workflows/DockerfileSlim ./
          
          git add .github/workflows/sync-fork.yml .github/workflows/build-docker-image.yml DockerfileSlim
          git commit -m "Add workflows and DockerfileSlim"
          git push --force origin master
          git push --force --tags origin master

  build-push-image:
    needs: sync-fork
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref: ${{ fromJSON(needs.sync-fork.outputs.refs ) }}
    steps:
      - name: Trigger workflow to build Docker image
        run: gh workflow run build-docker-image.yml --repo pkudrel/SeleniumBase --raw-field ref=${{ matrix.ref }}
        env:
         GH_TOKEN: ${{ github.token }}